name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          curl -LO https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-windows-x86_64.zip
          Expand-Archive cmake-3.21.0-windows-x86_64.zip -DestinationPath C:\CMake
          echo 'C:\CMake\bin' >> $env:Path
          cmake --version

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release
